# FriendlyChat Codelab

use_frameworks!
platform :ios, '13.0'

pod 'Firebase', '10.6.0'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/RemoteConfig'
pod 'Firebase/Storage'
pod 'Firebase/Crashlytics'
pod 'GoogleSignIn'

target 'FriendlyChatSwift' do
end
